# Macro file for the initialization of example B3
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
#
# Initialize kernel
/run/initialize
#
# create empty scene
#
/vis/scene/create
# open graphics (opengl QT)
/vis/open OGL
# Draw trajectories at end of event, showing trajectory points as
# markers of size 2 pixels
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set e- yellow
/vis/modeling/trajectories/drawByCharge-0/set e+ yellow
/vis/modeling/trajectories/drawByCharge-0/set gamma green
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# To draw gammas only
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To draw charged particles only
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options available with /vis/modeling and /vis/filtering.
# For example, select colour by particle ID
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
#/vis/modeling/trajectories/drawByParticleID-0/set e+ red
#/vis/modeling/trajectories/drawByParticleID-0/set pi- blue
#/vis/modeling/trajectories/drawByParticleID-0/set pi+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set kaon- red
#/vis/modeling/trajectories/drawByParticleID-0/set kaon+ red
#/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set anti_proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set neutron white
#/vis/modeling/trajectories/drawByParticleID-0/set anti_neutron white
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
# remove low energy stuff
#/vis/filtering/trajectories/create/attributeFilter
#/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
#/vis/filtering/trajectories/attributeFilter-0/addInterval 2 MeV 1000 GeV
# reenable auto refresh
/vis/viewer/set/autoRefresh true
/vis/viewer/addCutawayPlane 0 0 0 m 1 0 0
#
# At end of each run, an automatic flush causes graphical output.
#/run/beamOn 1
# When you exit Geant4, you will find a file called scene-0.heprep.zip.
# Unzipping this will give you three separate HepRep files suitable for
# viewing in WIRED.
# The first file will contain just detector geometry.
# The second file will contain the detector plus one event.
# The third file will contain the detector plus ten events.
